sudo: required

env:
 matrix:
  - DIST=ubuntu
    VER=20.04
  - DIST=centos
    VER=7
  - DIST=opensuse.leap
    VER=15

language: c

language: java
jdk: openjdk8

services:
 - docker

before_install:
 - echo ${DIST}:${VER}
 - git submodule init
 - git submodule update
 - docker pull ${DIST/.//}:${VER}

script:
 - docker build -f utils/docker/Dockerfile.${DIST}.${VER} -t daos/$DIST --build-arg NOBUILD=1 --build-arg UID=$UID .
 - docker run -v $PWD:/home/daos/daos:z daos/$DIST /bin/bash -c "scons --build-deps=yes install"
